### ISSUE TITLE
Copy Docs

### ISSUE THREAD

**Issue by quasiben** [hiroyuki-sato/openucx-docs#1]
@hiroyuki-sato would you mind we copied a lot of this material into the ucx-py docs ?
https://ucx-py.readthedocs.io/en/latest/

**Comment by hiroyuki-sato** [comment]
Hello, @quasiben 

Of course, Please feel free to copy the contents.

By the way, does [this doc](https://ucx-py.readthedocs.io/en/latest/) ucx-py specific?
I'll contribute to https://openucx.readthedocs.io/en/master/ in the future.
I hope to maintain these contents with you. 

P.S.
code_reading directory is just my memo. I think it not useful for you.

**Comment by quasiben** [comment]
thank you @hiroyuki-sato !

correct, the first doc is ucx-py specific but there will, of course be some overlap.  Contributing your input to https://openucx.readthedocs.io/en/master/ would be very helpful for UCX users such as myself.

**Comment by hiroyuki-sato** [comment]
Merged
https://ucx-py.readthedocs.io/en/latest/glossary.html

@quasiben Thank you!
